### ISSUE TITLE
Delay in new sites in STNWeb showing up in search results, map

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#226]
Marie created a site in Illinios [ILBUR16072] next to this one, but as you can see, it doesn't appear on the map even after about 15 mintues.

<img width="1027" alt="nearby site" src="https://cloud.githubusercontent.com/assets/12058013/15690555/131e98e8-2752-11e6-80d0-04a6d40f7fc0.PNG">

But, we know it's in the DB, because if you go to the neighboring site, and view the map, you see it there.

<img width="1031" alt="hasafriend" src="https://cloud.githubusercontent.com/assets/12058013/15690559/1521e668-2752-11e6-9519-293164bd344c.PNG">

The new site also does not appear in search results:

<img width="1033" alt="notinsearch" src="https://cloud.githubusercontent.com/assets/12058013/15690561/167d9cfa-2752-11e6-8fc3-3bd493a624e3.PNG">

**Comment by HansVraga** [comment]
You can also see searching directly works, even though it still won't show up in search.

![image](https://cloud.githubusercontent.com/assets/12058013/15690772/26ff77f0-2753-11e6-8c64-689e5e005e39.png)

**Comment by HansVraga** [comment]
Formulating a testing plan. Lets work backwards. 
- [ ]  1. @troddick verify services are returning what we're seeing in these screenshots. If need be, I will be available to create another site to recreate the issue. If not, this could be some local caching issue.
- [ ]  2. @troddick verify that the DB is returning what we're seeing in these screenshots to the services. If not it could be an issue with handling and passing the data within the Webservices.
- [ ]  3. @aaronstephenson If those first two come up empty, we're going to have to take another look at the database, and figure out why it's returning what it is, and if we have options. 

(initially assigned @BlakeDraper and @jknewson by mistake, meant to just keep them in the loop).

**Comment by HansVraga** [comment]
For troubleshooting, it appears this site still isn't on the map or returning as results - perhaps we have a different issue? All the sites returning on the search have at least one OP or attached 'thing' - maybe sites with nothing attached don't appear?

**Comment by BlakeDraper** [comment]
The endpoint used to populate the map is this (WALUIGI is the event here): https://stntest.wim.usgs.gov/STNServices2P/Events/127/Sites.json, and the new site (ILBUR16072) does not come back from that request. 

But the little inset map on site dashboard uses the buffer endpoint which does not respect events, and ILBUR16072 does come back from that result, as we can see. So I searched for sites in Illinois under event WALUIGI, and ILBUR16072 does not appear. 

So the answer is, somehow this site was created without being associated with the WALUIGI event. That's why it doesn't appear on the main map.

@troddick

**Comment by troddick** [comment]
A site is not associated with an event until either a HWM or a Sensor is created at it with an Event.
The filtered Sites endpoint used on the Site tab to search for sites should return all sites (if no event is chosen) because the first action is to get all the Sites and then it filters them down based on the parameters passed in.

**Comment by BlakeDraper** [comment]
Well then there you go - Hans was on to it with the not having any sensors/HWMs at it.

**Comment by BlakeDraper** [comment]
So this is an issue that will eventually be addressed by the showing of non-event-associated sites on the map, which is currently questioned out to Marie.

**Comment by HansVraga** [comment]
Closing - filing under "user error" - this is working as designed!
As Blake said above, once #222 is complete this will help communicate to the user what is happening.
