### ISSUE TITLE
Allow for entry of military time

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#304]
Field folks are often trained to enter things via military time (rightfully so, I say!)
It threw off some folks responding to the Matthew event. We should work our date/time fields to allow for military time.

If a military time is entered, remove the display of AM/PM.

**Comment by troddick** [comment]
I'm not super enthused about this one. I am already doing some finagling the time as it is since the db stores it in UTC, but the browser wants to display it in the machine's timezone and firefox and chrome both handle time differently and I had to add a bunch to get it to work consistently. 
Keeping this open but on the backburner for now.

**Comment by HansVraga** [comment]
Back-burner is fine.
