### ISSUE TITLE
Add "label" field to HWMs

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#329]
Field users typically label HWMs and this could be useful - especially when sorting through different hwms at the same site. We should add a text field called "Label", auto-populate it when a new HWM is created with "M1" (increment for each new HWM), and let the user edit it if they have their own labeling scheme. these labels should not exceed 6 characters, and we should enforce all HWMs attached to the same site to have a unique label.

**Comment by HansVraga** [comment]
Existing HWMs should have their label auto-populated, starting with the oldest at each site getting "M1" and increment for any others at that site.

**Comment by troddick** [comment]
Would need more info on this. Where is "M" coming from, or is that just a random letter chosen to illustrate an example? Slightly confusing: 'Let them have control of changing the label, but have all hwms unique to the site it belongs to.'
What to use for auto-populating on POST, restrictions on what they can edit it to after creation, populating all existing hwm's label field = required information in order to move forward.

**Comment by troddick** [comment]
![image](https://cloud.githubusercontent.com/assets/1580076/22656275/79cd921c-ec58-11e6-9b07-1f4c7d8d4d48.png)

HWM Label: [ input autopopulated with hwm-{#ofHWMs at site+1} ] limit to 12 characters with tooltip "Label for distinguishing hwm from other hwms at this site-event"
make sure they don't edit it to be the same label of a hwm at this site-event. (distinct)

-show {label } {date} - { height} in hwm List accordion.

**Comment by troddick** [comment]
Question:
This should be a required field, correct?

**Comment by tkoenigusgs** [comment]
looks good
