### ISSUE TITLE
Historic HWM Entry - Site-HWM Lat/Long Validation check

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#344]
From Todd
>Let's add a check between the Lat/Lon of the HWM that I am entering and the Lat/Lon of the Site that I am assigning to it.  If it is more than 2000ft distance, let's warn them that they may have goofed that up.  That will do a better job of trapping bad coordinates than our check on min/max lat/lon.

**Comment by troddick** [comment]
The list of sites they get is in response to a distance (253ft) around the lat/long they provided for that hwm (row). They can not click the down-arrow on SiteNo until they enter a hwm lat/long in that row.
They can ignore those in the nearby site list and create a new site, but this will populate the lat/long of the new site with the lat/long of the hwm's lat/long from that row.
I could add a check to compare what they changed it to (in the site create portion) to the lat/long of the hwm at that row, but I'm not sure that would be useful, as that isn't anything stored in the db, but rather just the lat/long of a hwm they wish to create. They could click Create (the site will be created and that siteNo will be added to that row), but then they could then go and change the lat/long of the row (hwm's lat/long). Maybe a second check (again) to see if what they change it (the hwm row lat/long cell vals) to matches the site's lat/long (if there is one yet, because this would get fired when they update the lat/long irregardless if a site has been created yet). That could cause an issue... 

I feel that the current way (site list based on buffer distance of hwm's lat/long, new site creation uses lat/long of the hwm to populate the site's lat/long) goes a long way to ensure they use a correct lat/long, in addition to the existing range validation that's in place.
Open to further discussion, of course.
