### ISSUE TITLE
hwm lat/long checks against site

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/STNWeb#348]
When creating hwm, in addition to range checks on lat/long, also check that the lat/long is within certain distance of the site's lat/long that we are adding it to.

**Comment by troddick** [comment]
Question:
How aggressive do we want to be with the lat/long checks? Currently, if the value is outside the range of acceptable values (positive for a long, greater than -175, etc), I'm only showing a warning modal that the longitude needs to be between -175.0 and -60.0. They can still save the hwm without fixing the issue. 
Should I be clearing the value or disabling the 'Create' / 'Save' button until they fix it? I could see how clearing it would be aggravating to the user.

**Comment by troddick** [comment]
done in stntest

**Comment by tkoenigusgs** [comment]
I like the popup.  I like that it doesn't keep the user from finishing the task, even if they don't change the lat/lon value.  This is appropriate because it is only a warning.  I find the "232 feet" a curious threshold, but I'm cool with it.  I only think the language needs to change to more of a warning, not a "must".  Currently, it says, "Longitude must be within 232 ft from the site's longitude".  I would change it to: "Lat/Lon places the HWM more than 232 ft from the site's Lat/Lon.  Please verify before continuing."
