### ISSUE TITLE
show sensor elevation value even if its 0

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/STNWeb#420]
![image](https://user-images.githubusercontent.com/1580076/36697062-8fb33edc-1b0b-11e8-87cf-ee69989f1894.png)

**Comment by lprivette** [comment]
Fix for this is in branch 418

**Comment by lprivette** [comment]
In test.

**Comment by tkoenigusgs** [comment]
I didn't really know how to test this because I can't see FEV for the test system.  If I remember correctly, this was a question raised by folks in Florida, and we decided that FEV should display "0" when "0" was entered in STN, and FEV should display "--" (not "0") when "--" is entered in STN.  If there's a way to bring up FEV for the test system, I can look at this.  Otherwise, I guess we test it in production.

**Comment by lprivette** [comment]
STNWeb wasn't showing '0' for the sensor elevation (which is where this screenshot is taken?), so I changed it there to show '0' not the "--".

We already made the changes to fev/stnpublicinfo for HWMs https://github.com/USGS-WiM/STNPublicInfo/commit/44a2eea07e3ddba50f4368287702f4935e0ecf1d. You can see 0's on this site https://stn.wim.usgs.gov/STNPublicInfo/#/HWMPage?Site=24252&HWM=27253. 

I got test instance stood up for fev and stnpublicinfo https://test.wim.usgs.gov/FEV/. You may need to hard refresh in order to pull in the url change to the services I checked sensors and looks like I need to make the change there to display '0'. I created an issue for it here https://github.com/USGS-WiM/STNPublicInfo/issues/7

**Comment by lprivette** [comment]
https://github.com/USGS-WiM/STNPublicInfo/issues/7 is completed in test as well

**Comment by tkoenigusgs** [comment]
Looks good from here.  Thanks!

**Comment by lprivette** [comment]
in prod
